/*
 * Vencord, a modification for Discord's desktop app
 * Copyright (c) 2022 Vendicated and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import "./IconsTab.css";

import { Margins } from "@utils/margins";
import { Clickable, Forms, Icons, React, TextInput } from "@webpack/common";

import { openIconModal } from "./IconModal";
import { SettingsTab, wrapTab } from "./shared";
// findByProps("colors", "layout")

const IconNames = [
    "AIcon",
    "AccessibilityIcon",
    "AchievementsIcon",
    "ActivitiesIcon",
    "ActivitiesPlusIcon",
    "AirplayIcon",
    "AnalyticsIcon",
    "AngleBracketsIcon",
    "AnnouncementsChatIcon",
    "AnnouncementsIcon",
    "AnnouncementsLockIcon",
    "AnnouncementsWarningIcon",
    "AppleBrandLightIcon",
    "AppleNeutralIcon",
    "AppsIcon",
    "ArrowAngleDownLeftIcon",
    "ArrowAngleLeftDownIcon",
    "ArrowAngleLeftUpIcon",
    "ArrowAngleRightDownIcon",
    "ArrowAngleRightUpIcon",
    "ArrowAngleUpLeftIcon",
    "ArrowLargeDownIcon",
    "ArrowLargeLeftIcon",
    "ArrowLargeRightIcon",
    "ArrowLargeUpIcon",
    "ArrowSmallDownIcon",
    "ArrowSmallLeftIcon",
    "ArrowSmallRightIcon",
    "ArrowSmallUpIcon",
    "ArrowsLeftRightIcon",
    "ArrowsUpDownIcon",
    "AsteriskIcon",
    "AtIcon",
    "AttachmentIcon",
    "BIcon",
    "BackspaceIcon",
    "BadgeIcon",
    "BeakerIcon",
    "BellIcon",
    "BellSlashIcon",
    "BellZIcon",
    "BicycleIcon",
    "BillIcon",
    "BluetoothIcon",
    "BlurBackgroundIcon",
    "BoldIcon",
    "BookCheckIcon",
    "BookmarkIcon",
    "BookmarkOutlineIcon",
    "BoostTier1Icon",
    "BoostTier1SimpleIcon",
    "BoostTier2Icon",
    "BoostTier2SimpleIcon",
    "BoostTier3Icon",
    "BoostTier3SimpleIcon",
    "BrowserCheckeredIcon",
    "BrowserIcon",
    "BrowserLinkIcon",
    "BrowserPlusIcon",
    "BrowserQuestionMarkIcon",
    "BugIcon",
    "CalendarIcon",
    "CalendarMinusIcon",
    "CalendarPlusIcon",
    "CalendarRetryIcon",
    "CalendarXIcon",
    "CameraIcon",
    "CameraSwapIcon",
    "CarIcon",
    "ChannelListIcon",
    "ChannelListMagnifyingGlassIcon",
    "ChannelListMinusIcon",
    "ChannelListPlusIcon",
    "ChannelListRetryIcon",
    "ChannelNotificationIcon",
    "ChannelsFollowedIcon",
    "ChatArrowRightIcon",
    "ChatCheckIcon",
    "ChatDotsIcon",
    "ChatEyeIcon",
    "ChatIcon",
    "ChatMarkUnreadIcon",
    "ChatMinusIcon",
    "ChatPlusIcon",
    "ChatRetryIcon",
    "ChatSlowModeIcon",
    "ChatSmileIcon",
    "ChatSpeakIcon",
    "ChatWarningIcon",
    "ChatXIcon",
    "CheckmarkLargeBoldIcon",
    "CheckmarkLargeIcon",
    "CheckmarkSmallBoldIcon",
    "CheckmarkSmallIcon",
    "ChevronLargeDownIcon",
    "ChevronLargeLeftIcon",
    "ChevronLargeRightIcon",
    "ChevronLargeUpIcon",
    "ChevronSmallDownIcon",
    "ChevronSmallLeftIcon",
    "ChevronSmallRightIcon",
    "ChevronSmallUpIcon",
    "CircleCheckIcon",
    "CircleInformationIcon",
    "CircleMinusIcon",
    "CirclePlayIcon",
    "CirclePlusIcon",
    "CircleQuestionIcon",
    "CircleWarningIcon",
    "CircleXIcon",
    "ClipboardCheckIcon",
    "ClipboardListIcon",
    "ClipsGalleryIcon",
    "ClipsIcon",
    "ClockIcon",
    "ClockWarningIcon",
    "ClockXIcon",
    "CloudDownloadIcon",
    "ClydeIcon",
    "CollapseListIcon",
    "CompassIcon",
    "ConnectionAverageIcon",
    "ConnectionBadIcon",
    "ConnectionFineIcon",
    "ConnectionUnknownIcon",
    "ContactsIcon",
    "CopyIcon",
    "CreditCardIcon",
    "CropIcon",
    "CrownIcon",
    "CrunchyrollBrandLightIcon",
    "CrunchyrollNeutralIcon",
    "DenyIcon",
    "DoorEnterIcon",
    "DoorExitIcon",
    "DoubleCheckmarkIcon",
    "DownloadIcon",
    "DpadIcon",
    "DragIcon",
    "EducationIcon",
    "EmbedIcon",
    "EnvelopeIcon",
    "ExpandGifIcon",
    "ExperimentalLootboxIcon",
    "ExperimentalPineappleSpongebobIcon",
    "EyeDropperIcon",
    "EyeIcon",
    "EyePlusIcon",
    "EyeSlashIcon",
    "FacebookNeutralIcon",
    "FileDenyIcon",
    "FileIcon",
    "FileUpIcon",
    "FileWarningIcon",
    "FiltersHorizontalIcon",
    "FireIcon",
    "FlagIcon",
    "FlagMinusIcon",
    "FlagPlusIcon",
    "FlagRetryIcon",
    "FlashIcon",
    "FlipHorizontalIcon",
    "FlipVerticalIcon",
    "FolderIcon",
    "FolderPlusIcon",
    "FoodIcon",
    "ForumIcon",
    "ForumLockIcon",
    "ForumWarningIcon",
    "FriendsIcon",
    "FullscreenEnterIcon",
    "FullscreenExitIcon",
    "GameControllerIcon",
    "GifIcon",
    "GiftIcon",
    "GlobeEarthIcon",
    "GridHorizontalIcon",
    "GridSquareIcon",
    "GridVerticalIcon",
    "GroupArrowDownIcon",
    "GroupArrowRightIcon",
    "GroupIcon",
    "GroupMinusIcon",
    "GroupPlusIcon",
    "GroupRetryIcon",
    "HammerIcon",
    "HammerMinusIcon",
    "HammerPlusIcon",
    "HammerRetryIcon",
    "HammerXIcon",
    "HandRequestSpeakIcon",
    "HandRequestSpeakListIcon",
    "HashmarkIcon",
    "HdIcon",
    "HeadphonesDenyIcon",
    "HeadphonesIcon",
    "HeadphonesSlashIcon",
    "HeartIcon",
    "HeartOutlineIcon",
    "HomeIcon",
    "HomeSlashIcon",
    "HourglassIcon",
    "HubIcon",
    "IdIcon",
    "ImageFileIcon",
    "ImageFileUpIcon",
    "ImageIcon",
    "ImageLockIcon",
    "ImagePlusIcon",
    "ImageSparkleIcon",
    "ImageTextIcon",
    "ImageWarningIcon",
    "ImagesIcon",
    "InboxIcon",
    "InstagramNeutralIcon",
    "InventoryIcon",
    "ItalicIcon",
    "KeyIcon",
    "KeyboardIcon",
    "LanguageIcon",
    "LaptopPhoneIcon",
    "LettersIcon",
    "LightbulbIcon",
    "LinkExternalMediumIcon",
    "LinkExternalSmallIcon",
    "LinkIcon",
    "LinkPlusIcon",
    "ListBulletsIcon",
    "ListNumberedIcon",
    "LocationIcon",
    "LockIcon",
    "LockUnlockedIcon",
    "MagicWandIcon",
    "MagnifyingGlassIcon",
    "ManaIcon",
    "MaximizeIcon",
    "MedalIcon",
    "MenuIcon",
    "MicrophoneArrowRightIcon",
    "MicrophoneDenyIcon",
    "MicrophoneIcon",
    "MicrophoneSlashIcon",
    "MinimizeIcon",
    "MinusIcon",
    "MobilePhoneControllerIcon",
    "MobilePhoneIcon",
    "MobilePhonePlusIcon",
    "MobilePhoneSettingsIcon",
    "MobilePhoneShareIcon",
    "MobilePhoneSpeakerIcon",
    "MobilePhoneVideoIcon",
    "MobilePhoneXIcon",
    "ModerationIcon",
    "MoreHorizontalIcon",
    "MoreVerticalIcon",
    "MusicIcon",
    "MusicSlashIcon",
    "NatureIcon",
    "NearbyScanIcon",
    "NewUserIcon",
    "NewUserSimpleIcon",
    "NintendoSwitchNeutralIcon",
    "NitroWheelIcon",
    "ObjectIcon",
    "PaintPaletteIcon",
    "PaintbrushThickIcon",
    "PaintbrushThickMinusIcon",
    "PaintbrushThickPlusIcon",
    "PaintbrushThickRetryIcon",
    "PaintbrushThinIcon",
    "PaintbrushThinMinusIcon",
    "PaintbrushThinPlusIcon",
    "PaintbrushThinRetryIcon",
    "PaperIcon",
    "PaperPlusIcon",
    "PauseIcon",
    "PencilIcon",
    "PencilSparkleIcon",
    "PhoneCallIcon",
    "PhoneHangUpIcon",
    "PhoneIcon",
    "PiggyBankIcon",
    "PinIcon",
    "PinUprightIcon",
    "PinUprightSlashIcon",
    "PlayIcon",
    "PlaystationNeutralIcon",
    "PlusLargeIcon",
    "PlusMediumIcon",
    "PlusSmallIcon",
    "PollsIcon",
    "PrivacyAndSafetyIcon",
    "PuzzlePieceIcon",
    "PuzzlePieceMinusIcon",
    "PuzzlePiecePlusIcon",
    "PuzzlePieceRetryIcon",
    "QrCodeIcon",
    "QuestsIcon",
    "QuoteIcon",
    "ReactionIcon",
    "ReceiptIcon",
    "RecordPlayerIcon",
    "RedoIcon",
    "RefreshIcon",
    "RemixIcon",
    "RetryIcon",
    "RibbonIcon",
    "RobotIcon",
    "RotateIcon",
    "ScienceIcon",
    "ScreenArrowIcon",
    "ScreenIcon",
    "ScreenSlashIcon",
    "ScreenStreamIcon",
    "ScreenSystemRequirementsIcon",
    "ScreenXIcon",
    "SendMessageIcon",
    "ServerGridIcon",
    "ServerIcon",
    "SettingsArrowUpIcon",
    "SettingsCircleIcon",
    "SettingsIcon",
    "SettingsInfoIcon",
    "SettingsPlusIcon",
    "ShareIcon",
    "ShieldAtIcon",
    "ShieldIcon",
    "ShieldLockIcon",
    "ShieldUserIcon",
    "ShopIcon",
    "ShopMinusIcon",
    "ShopPlusIcon",
    "ShopSparkleIcon",
    "SignPostIcon",
    "SlashBoxIcon",
    "SlashIcon",
    "SlashMinusIcon",
    "SlashPlusIcon",
    "SlashRetryIcon",
    "SoundboardIcon",
    "SoundboardSlashIcon",
    "SparklesIcon",
    "SpeedometerIcon",
    "SpoilerIcon",
    "StaffBadgeIcon",
    "StageIcon",
    "StageListIcon",
    "StageLockIcon",
    "StageMinusIcon",
    "StageModeratorIcon",
    "StagePlusIcon",
    "StageRetryIcon",
    "StageXIcon",
    "StampIcon",
    "StarIcon",
    "StarOutlineIcon",
    "StarShootingIcon",
    "StickerDeadIcon",
    "StickerIcon",
    "StickerMinusIcon",
    "StickerPlusIcon",
    "StickerRetryIcon",
    "StickerSadIcon",
    "StickerSmallIcon",
    "StickerWink1Icon",
    "StickerWink2Icon",
    "StopIcon",
    "StrikethroughIcon",
    "SuperReactionIcon",
    "TagIcon",
    "TagsIcon",
    "TextIcon",
    "TextLockIcon",
    "TextWarningIcon",
    "ThemeDarkIcon",
    "ThemeLightIcon",
    "ThemeMidnightIcon",
    "ThreadIcon",
    "ThreadLockIcon",
    "ThreadMinusIcon",
    "ThreadPlusIcon",
    "ThreadRetryIcon",
    "ThreadWarningIcon",
    "ThumbsDownIcon",
    "ThumbsUpIcon",
    "TicketIcon",
    "TiktokNeutralIcon",
    "TimerIcon",
    "TopicsIcon",
    "TrainIcon",
    "TrashIcon",
    "TreehouseIcon",
    "TrophyIcon",
    "TvIcon",
    "TwitterNeutralIcon",
    "UnderlineIcon",
    "UndoIcon",
    "UnknownGameIcon",
    "UnsendIcon",
    "UploadIcon",
    "UserArrowDiagonalBottomRightIcon",
    "UserCheckIcon",
    "UserCircleIcon",
    "UserCircleStatusIcon",
    "UserClockIcon",
    "UserIcon",
    "UserMinusIcon",
    "UserPlayIcon",
    "UserPlusIcon",
    "UserRetryIcon",
    "UserSquareIcon",
    "UserStatusIcon",
    "VideoIcon",
    "VideoLockIcon",
    "VideoSlashIcon",
    "VoiceBluetoothIcon",
    "VoiceLockIcon",
    "VoiceLowIcon",
    "VoiceNormalIcon",
    "VoiceWarningIcon",
    "VoiceXIcon",
    "WalletIcon",
    "WarningIcon",
    "WaveformIcon",
    "WaveformSlashIcon",
    "WebhookIcon",
    "WebhookPlusIcon",
    "WidgetsIcon",
    "WidgetsMinusIcon",
    "WidgetsPlusIcon",
    "WidgetsRetryIcon",
    "WindowLaunchIcon",
    "WindowReturnIcon",
    "WindowTopIcon",
    "WindowTopOutlineIcon",
    "WrenchIcon",
    "XLargeBoldIcon",
    "XLargeIcon",
    "XNeutralIcon",
    "XSmallBoldIcon",
    "XSmallIcon",
    "XboxNeutralIcon",
    "YoutubeNeutralIcon",
];

function RenderIcons({ search }: { search: string; }) {
    return <div className="vc-icons-tab-grid-container"
        style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(64px, 1fr))",
            gap: "8px",
        }}
    >
        {(IconNames.filter(name => {
            const words = name.replace(/([A-Z]([a-z]+)?)/g, " $1").toLowerCase().split(" ");
            const searchKeywords = search.toLowerCase().split(" ");
            return searchKeywords.every(keyword => words.includes(keyword)) || words.every(keyword => searchKeywords.includes(keyword)) || name.toLowerCase().includes(search.toLowerCase());
        }).map(iconName => {
            const Icon = Icons[iconName];
            return <React.Fragment key={iconName}>
                <div className="vc-icon-box">
                    <Clickable onClick={() => openIconModal(iconName, Icon as any)}>
                        <div className="vc-icon-container">
                            <Icon className="vc-icon-icon" size="xxl" />
                        </div>
                    </Clickable>
                    <Forms.FormTitle className="vc-icon-title" tag="h3">{iconName}</Forms.FormTitle>
                </div>
            </React.Fragment>;
        }))}</div>;
}

function IconsTab() {
    const [search, setSearch] = React.useState<string>("");

    return (
        <SettingsTab title="Icons">
            <Forms.FormTitle className={Margins.top8} tag="h1">Discord Icons</Forms.FormTitle>
            <TextInput autoFocus value={search} placeholder="Search for an icon..." onChange={setSearch} />
            <RenderIcons search={search} />
        </SettingsTab>
    );
}

export default IS_DEV ? wrapTab(IconsTab, "IconsTab") : null;
